name: CI Pipeline

on:
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install
      - name: Run backend linting
        working-directory: ./backend
        run: npx eslint src
      - name: Run backend tests
        working-directory: ./backend
        run: npm test
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
