name: CI Pipeline

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop, setup-remote-state-clean]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # === BACKEND ===
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Fix ESLint permissions
        working-directory: ./backend
        run: chmod +x ./node_modules/.bin/eslint

      - name: Fix Jest permissions
        working-directory: ./backend
        run: chmod +x ./node_modules/.bin/jest

      - name: Run backend linting
        working-directory: ./backend
        run: npx eslint src
        continue-on-error: true

      - name: Run backend tests
        working-directory: ./backend
        run: npm test
        continue-on-error: true

      - name: Delete ESLint cache manually (if it exists)
        working-directory: ./backend
        run: rm -f .eslintcache

      # === FRONTEND ===
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
